- hosts: all
  roles:
  - linux-system-roles.kdump
  tasks:
  - name: update kernel
    dnf:
      state: latest
      name: 
      - kernel
      - kernel-debuginfo
      enablerepo: updates-debuginfo
    notify: reboot_system
  - yum:
      state: latest
      name:
      - vim
      - gdb
      - lsof
      - net-tools
      - tcpdump
      - wireshark
      - strace
      - ltrace
      - systemtap
      - perf
      - sysstat
      - procps-ng
      - bind-utils
      - nfs-utils
      - cifs-utils
      - gcc
      - gcc-c++
      - make
      - ruby
      - ruby-irb
      - git
      - ctags
      - global
      - rpm-build
      - mailx
      - mutt
      - telnet
      - psmisc
      - man-pages
      - rust
      - autoconf
      - automake
      - crash
      - tmux
      - pcp-zeroconf
      - grafana-pcp
      - redis
  - lineinfile:
      path: /etc/grafana/grafana.ini
      regexp: ^allow_loading_unsigned_plugins
      line: allow_loading_unsigned_plugins = pcp-redis-datasource
  - copy:
      dest: /root/.vimrc
      content: |
        set noswapfile
        set number
        set expandtab
        set tabstop=2
        set shiftwidth=2
        set paste
  - file:
      path: /root/.vim/plugin
      state: directory
    tags: gtags
  - copy:
      src: /usr/share/gtags/gtags.vim
      dest: /root/.vim/plugin
    tags: gtags
  - blockinfile:
      path: /root/.bashrc
      block: |
        export SYSTEMD_EDITOR=vi
        alias script='script /tmp/`date +%y%m%d-%H%M%S`.log'
  - lineinfile:
      path: /etc/systemd/system.conf
      regex: DefaultLimitCORE
      line: DefaultLimitCORE=infinity
  - blockinfile:
      path: /etc/sysctl.conf
      block: |
        kernel.core_pattern=/tmp/core.%e.%p
        fs.suid_dumpable=2
  - user:
      name: root
      generate_ssh_key: yes
  - service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
    - pmcd
    - pmlogger
    - grafana-server
    - redis
    - pmproxy
  - firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
    loop:
      - 3000
      - 44322
  handlers:
  - name: reboot_system
    reboot:
      test_command: date
