---
- name: docker
  hosts: all
  tasks:
  - dnf:
      state: absent
      name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
  - dnf:
      state: present
      name: dnf-plugins-core
  - command: >
      dnf config-manager
      --add-repo
      https://download.docker.com/linux/fedora/docker-ce.repo
  - yum:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  - service:
      name: docker
      state: started
      enabled: yes
  
