- hosts: servers
  tasks:
#    - command: 'dnf -y update'
#    - command: 'dnf -y debuginfo-install kernel'
    - yum:
        state: latest
        name:
          - vim
          - gdb
          - lsof
          - net-tools
          - tcpdump
          - wireshark
          - strace
          - ltrace
          - systemtap
          - perf
          - sysstat
          - procps-ng
          - bind-utils
          - nfs-utils
          - cifs-utils
          - gcc
          - gcc-c++
          - make
          - ruby
          - ruby-irb
          - git
          - ctags
          - global
          - rpm-build
          - mailx
          - mutt
          - telnet
          - psmisc
          - man-pages
          - rust
          - autoconf
          - automake
          - cracklib-devel
          - cyrus-sasl-devel
          - krb5-devel
          - libdb-devel
          - libevent-devel
          - libicu-devel
          - libtool
          - ncurses-devel
          - net-snmp-devel
          - nspr-devel
          - nss-tools
          - nss-devel
          - openldap-clients
          - openldap-devel
          - openssl-devel
          - openssl-perl
          - pam-devel
          - pcre-devel
          - python3-argparse-manpage
          - python3-ldap
          - rpm-devel
          - gettext-devel
          - libtalloc-devel
          - libtdb-devel
          - libtevent-devel
          - libldb-devel
          - libdhash-devel
          - libcollection-devel
          - libini_config-devel
          - c-ares-devel
          - glib2-devel
          - dbus-devel
          - docbook-style-xsl.noarch
          - libsemanage-devel
          - python3-devel
          - libxslt-devel
          - flex
          - bison
          - samba-devel
          - python2-devel
          - readline-devel
          - perl-LDAP
          - perl-Date-Manip
          - systemd-devel
          - python2-setuptools
          - dwarves
          - crash
          - tmux
    - systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      with_items:
        - firewalld
    - selinux:
       policy: targeted
       state: permissive
    - copy:
        dest: /root/.vimrc
        content: |
          set noswapfile
          set number
          set expandtab
          set tabstop=8
          set shiftwidth=2
          set paste
    - file:
        path: /root/.vim/plugin
        state: directory
      tags: gtags
    - copy:
        src: /usr/share/gtags/gtags.vim
        dest: /root/.vim/plugin
      tags: gtags
    - blockinfile:
        path: /root/.bashrc
        block: |
          export SYSTEMD_EDITOR=vi
          alias script='script /tmp/`date +%y%m%d-%H%M%S`.log'
    - lineinfile:
        path: /etc/systemd/system.conf
        regex: DefaultLimitCORE
        line: DefaultLimitCORE=infinity
    - blockinfile:
        path: /etc/sysctl.conf
        block: |
          kernel.core_pattern=/tmp/core.%e.%p
          fs.suid_dumpable=2
    - user:
        name: root
        generate_ssh_key: yes
    - name: Make directory
      file:
        path: /root/GitRepos
        state: directory
    - name: Clone git repos
      git:
        repo: "{{ item }}"
        dest: '/root/GitRepos/{{ item | regex_search("([^/]+).git$") | regex_replace(".git", "") }}'
      with_items:
        - https://github.com/performancecopilot/pcp.git
    - user:
        name: pcp
    - user:
        name: pcpqa
        groups:
          - pcp
    - lineinfile:
        create: yes
        path: /etc/sudoers.d/pcpqa
        regexp: "^pcpqa"
        line: "pcpqa   ALL=(ALL) NOPASSWD: ALL"
