- hosts: pcp-grafana-server
  tasks:
  - yum:
      - pcp-zeroconf
      - grafana-pcp
      - redis
  - lineinfile:
      path: /etc/grafana/grafana.ini
      regexp: ^allow_loading_unsigned_plugins
      line: allow_loading_unsigned_plugins = pcp-redis-datasource
  - service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
    - pmcd
    - pmlogger
    - grafana-server
    - redis
    - pmproxy
  - firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
    loop:
      - 3000
      - 44322
