- hosts: all
  tasks:
  - yum:
      state: latest
      name:
      - gcc
      - gcc-c++
      - make
      - git
      - autoconf
      - automake
      - cracklib-devel
      - cyrus-sasl-devel
      - krb5-devel
      - libdb-devel
      - libevent-devel
      - libicu-devel
      - libtool
      - ncurses-devel
      - net-snmp-devel
      - nspr-devel
      - nss-tools
      - nss-devel
      - openldap-clients
      - openldap-devel
      - openssl-devel
      - openssl-perl
      - pam-devel
      - pcre-devel
      - python3-argparse-manpage
      - python3-ldap
      - rpm-devel
      - gettext-devel
      - libtalloc-devel
      - libtdb-devel
      - libtevent-devel
      - libldb-devel
      - libdhash-devel
      - libcollection-devel
      - libini_config-devel
      - c-ares-devel
      - glib2-devel
      - dbus-devel
      - docbook-style-xsl.noarch
      - libsemanage-devel
      - python3-devel
      - libxslt-devel
      - flex
      - bison
      - samba-devel
      - python2-devel
      - readline-devel
      - perl-LDAP
      - perl-Date-Manip
      - systemd-devel
      - python2-setuptools
      - dwarves
      - libpfm-devel
      - HdrHistogram_c-devel
      - avahi-devel
      - chan-devel
      - device-mapper-devel
      - postfix-perl-scripts
      - python3-jsonpointer
      - python3-openpyxl
      - python3-psycopg2
      - python3-rtslib
      - ragel
      - selinux-policy-devel
      - setools-console
      - perl-DBI
      - perl-generators
      - libuv-devel
      - libvarlink-devel
      - libvirt-python3
      - libibumad-devel
      - perl-DBD-MySQL
      - hicolor-icon-theme
      - python3-lxml
      - python3-requests
      - qt5-qtbase-devel
      - qt5-qtsvg-devel

